# Generated by Django 5.1.6 on 2025-02-26 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('class_number', models.CharField(max_length=10)),
                ('nomination', models.CharField(max_length=100)),
                ('startup_name', models.CharField(max_length=200)),
                ('startup_description', models.TextField()),
                ('presentation', models.FileField(upload_to='presentations/')),
                ('cover', models.ImageField(upload_to='covers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
