# Generated by Django 5.1.6 on 2025-03-10 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 10, 18, 50, 17, 236835)),
            preserve_default=False,
        ),
    ]
