# Generated by Django 5.1.7 on 2025-03-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Рейтинг заявок',
                'verbose_name_plural': 'Рейтинг заявок',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('women.application',),
        ),
    ]
