# Generated by Django 5.1.7 on 2025-03-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_applicationproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('regulations', models.FileField(upload_to='regulations/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='presentation',
            field=models.FileField(upload_to='presentations/'),
        ),
        migrations.AddField(
            model_name='application',
            name='contest',
            field=models.ForeignKey(default=2121, on_delete=django.db.models.deletion.CASCADE, to='women.contest'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'contest')},
        ),
    ]
