# Generated by Django 5.1.7 on 2025-04-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_contest_alter_application_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='application',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='startup_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='startup_name',
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Email'), ('number', 'Число'), ('file', 'Файл'), ('image', 'Изображение'), ('choice', 'Выбор из списка')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='women.contest')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='women.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.applicationfield')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='women.applicationfield')),
            ],
        ),
    ]
